name: Release Pack

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build dist
        run: npm run build

      - name: Pack tarball
        id: pack
        run: |
          TARBALL=$(npm pack | tail -n1)
          echo "tarball=$TARBALL" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.pack.outputs.tarball }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
